version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/finance_db
      - SECRET_KEY=your-secret-key-here
      - ALPHA_VANTAGE_API_KEY=CX8BNAM9IS9RDUWQ
      - COINAPI_KEY=62e27c13-2ce7-4584-972c-54b624b57dc2

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finance_db
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:  # Том для Redis